language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
before_install:
  - gem install bundler --pre
  - rm -rf Gemfile.lock
  - bundle update

before_script:
  - psql -c 'create database mnn_test;' -U postgres