# Using SOLR locally, with multiple cores 
# (Tomcat6 + SOLR-3.5 multiple-core)
# production:
#   solr:
#     hostname: 'pm.frederico-araujo.com'
#     port: 80
#     path: '/solr/mnn_production'

production:
  solr:
    hostname: '149.255.102.176' #'pm.frederico-araujo.com'
    port: 80
    path: '/solr/mnn_production'

development:
  solr:
    hostname: '127.0.0.1'
    port: 8080
    path: '/solr/mnn_development'

test:
  solr:
    hostname: '127.0.0.1'
    port: 8080
    path: '/solr/mnn_test'
