# Using SOLR locally, with multiple cores 
# (Tomcat6 + SOLR-3.5 multiple-core)

# production:
#   solr:
#     hostname: '149.255.102.176'
#     port: 80
#     path: '/solr/mnn_production'

production:
  solr:
    hostname: '127.0.0.1'
    port: 8080
    path: '/solr/mnn_development'
    auto_commit_after_request: false

development:
  solr:
    hostname: '127.0.0.1'
    port: 8980
    path: '/solr/collection1'
    auto_commit_after_request: false

test:
  solr:
    hostname: '127.0.0.1'
    port: 8080
    path: '/solr/mnn_test'
    auto_commit_after_request: false

